### ISSUE TITLE
Extension No Longer working

### ISSUE THREAD

**Issue by shintynash** [Krisa/Salesforce-Workbench#4]
The box is no longer lighting up blue on my tool bar when I login to salesforce, and so I can no longer use the extension. I am using a version of workbench running on my local network through http. The extension has stopped working on 2 different machines, and on all orgs I access whether sandbox or production, lightning or classic.

I don't see anything I have changed, though it could have been a background upgrade of chrome.

Any help or direction would be great, please let me know if you need extra information.

**Comment by 0cv** [comment]
In order to log you in, the extension reads the cookies and look especially for the `sid` cookie which corresponds to the session Id. I've just seen that on some production Org, the sid cookie is now set with the HttpOnly flag which makes it invisible for Javascript. There is however a workaround that a Chrome Extension with appropriate permission is able to read httpOnly cookies... Need some code change for that to happen.

**Comment by shintynash** [comment]
Krisa, Thanks, that is it, we recently changed settings in our orgs based on some security feedback to use HTTP only on the cookies. I hadn't connected the 2 things!

I had a play about with the code last night, and have it up and running with the chrome.cookies API, (rather hacked in as I am not a JS developer). 

I can share the changes, and if you don't think they are too hacked in perhaps they can be an update to the tool? I assume to upload a pull request here you would need to create a new branch and possibly open up access rights (sorry for the basic questions!). Any other preferred approaches?

**Comment by 0cv** [comment]
Glad if you make a PR. By using the Chrome API we probably can remove the trick to redirect to Salesforce.com when in Lightning in order to get the right sid cookie, which would speed up the login as well.
